# Power Semiconductor News Sources
# RSS feeds, X accounts, and Google Sheets for news collection

feeds:
  # Power Semiconductor Industry News (専門サイト)
  - https://www.powerelectronicsnews.com/feed/
  - https://semiengineering.com/feed/

  # Japanese Industry News (日本語)
  - https://rss.itmedia.co.jp/rss/2.0/eetimes.xml  # EE Times Japan

  # General Electronics (英語)
  - https://www.edn.com/feed/
  - https://www.embedded.com/feed/
  - https://www.electronics-lab.com/feed/

  # EV & Charging News
  - https://insideevs.com/feed/
  - https://electrek.co/feed/

  # Vendor Press Releases (example - add actual RSS feeds)
  # - https://www.infineon.com/rss/news
  # - https://www.wolfspeed.com/company/news/feed
  # - https://www.onsemi.com/site/rss/news.xml

# X (Twitter) accounts to monitor
x_accounts: []

# X RSS bridge (if using Nitter or similar)
x_rss_base: null
x_rss_accounts: []

# Google Sheets for manual curation
sheets: []
  # Example:
  # - id: "1ABC123..."
  #   gid: 0
  #   mapping:
  #     date: 0
  #     handle: 1
  #     text: 3
  #     url: 5
